### ISSUE TITLE
unable to run project

### ISSUE THREAD

**Issue by LuckyBlueDog** [vsigler/remote-log-console#5]
When I open the project through Intellij IDEA, sync fails. Here is the content. Can you provide me some solutions?
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bytedance/Downloads/remote-log-console-main/build.gradle.kts' line: 5

* What went wrong:
Plugin with id 'org.jetbrains.kotlin.jvm' was already requested at line 5

**Comment by vsigler** [comment]
Hmm, I just did a clean checkout and I can build it from commandline as well as open in Intellij IDEA (2024.2.1) just fine. What version are you using? Can you try a clean checkout?

**Comment by LuckyBlueDog** [comment]
thanks, I cleared the cache and it worked fine
