### ISSUE TITLE
Clicking the + option does not respond

### ISSUE THREAD

**Issue by LuckyBlueDog** [vsigler/remote-log-console#7]
In the new UI of Intellij IDEA 2024.2.3, clicking the + button does not activate the window window and the configuration window
![image](https://github.com/user-attachments/assets/4e81577b-9bc3-4fb3-a401-270564028423)

**Comment by vsigler** [comment]
@LuckyBlueDog I've just published version 1.1.3, can you update and check? It should be already fixed.

**Comment by LuckyBlueDog** [comment]
ok, thanks. It has been fixed
